[tool.black]
line-length = 120
verbose = 1
color = true
exclude = '''
/(
  | .mypy_cache
  | .pytest_cache
  | venv
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
src_paths = ["stable_gnn", "tests", "tutorials"]
skip = [".mypy_cache", ".pytest_cache" , "venv", "./venv"]

[tool.flake8]
max-line-length = 120
rst-roles = "class, func, ref"
rst-directives = "envvar, exception"
extend-ignore = "E203,E501,W503,D100,D105,D107,D400,D104,F401,DAR401"
docstring-convention = "pep257"
exclude=".git,*tests*,./venv,./build"
docstring_style = "sphinx"

[tool.mypy]
exclude=".git,*tests*,./venv,./build,.tests/"

ignore_missing_imports = true

# Disallow dynamic typing
disallow_any_unimported = false
disallow_subclassing_any = false

# Disallow untyped definitions and calls

disallow_untyped_calls = true
disallow_incomplete_defs = true

# Configuring warnings
warn_unused_ignores = true
warn_redundant_casts = true

# Misc things
strict_equality = true

[tool.pytest.ini_options]
addopts = "--capture=tee-sys -q"
log_cli = 1

testpaths = ["tests"]
